package hibernate;
// Generated 12 dic. 2023 21:03:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AuxDepartamentos generated by hbm2java
 */
public class AuxDepartamentos  implements java.io.Serializable {


     private int deptNo;
     private String dnombre;
     private String loc;
     private Set auxEmpleadoses = new HashSet(0);

    public AuxDepartamentos() {
    }

	
    public AuxDepartamentos(int deptNo, String dnombre, String loc) {
        this.deptNo = deptNo;
        this.dnombre = dnombre;
        this.loc = loc;
    }
    public AuxDepartamentos(int deptNo, String dnombre, String loc, Set auxEmpleadoses) {
       this.deptNo = deptNo;
       this.dnombre = dnombre;
       this.loc = loc;
       this.auxEmpleadoses = auxEmpleadoses;
    }
   
    public int getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(int deptNo) {
        this.deptNo = deptNo;
    }
    public String getDnombre() {
        return this.dnombre;
    }
    
    public void setDnombre(String dnombre) {
        this.dnombre = dnombre;
    }
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }
    public Set getAuxEmpleadoses() {
        return this.auxEmpleadoses;
    }
    
    public void setAuxEmpleadoses(Set auxEmpleadoses) {
        this.auxEmpleadoses = auxEmpleadoses;
    }




}


