package hibernate;
// Generated 9 dic. 2023 18:49:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private short empNo;
     private Departamentos departamentos;
     private byte nDepartamento;
     private String apellido;
     private String oficio;
     private short dir;
     private Date fechaAlta;
     private float salario;
     private float comision;

    public Empleados() {
    }

    public Empleados(short empNo, Departamentos departamentos, String apellido, String oficio, short dir, Date fechaAlta, float salario, float comision) {
       this.empNo = empNo;
       this.departamentos = departamentos;
       this.apellido = apellido;
       this.oficio = oficio;
       this.dir = dir;
       this.fechaAlta = fechaAlta;
       this.salario = salario;
       this.comision = comision;
    }
   
    public short getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(short empNo) {
        this.empNo = empNo;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getOficio() {
        return this.oficio;
    }
    
    public void setOficio(String oficio) {
        this.oficio = oficio;
    }
    public short getDir() {
        return this.dir;
    }
    
    public void setDir(short dir) {
        this.dir = dir;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public float getSalario() {
        return this.salario;
    }
    
    public void setSalario(float salario) {
        this.salario = salario;
    }
    public float getComision() {
        return this.comision;
    }
    
    public void setComision(float comision) {
        this.comision = comision;
    }

    public byte getnDepartamento() {
        return nDepartamento;
    }

    public void setnDepartamento(byte nDepartamento) {
        this.nDepartamento = nDepartamento;
    }


    public void imprimeColumnado(boolean cabecera){
        if(cabecera)
            System.out.printf("%-10s %-15s %-15s %-10s %-5s %-15s %-10s %-10s%n",
                    "EmpNo", "Departamento", "Apellido", "Oficio", "Dir", "Fecha Alta", "Salario", "Comisión");
        
        System.out.printf("%-10d %-15s %-15s %-10s %-5d %-15s %-10.2f %-10.2f%n",
                this.getEmpNo(), this.getDepartamentos().getDnombre(), this.getApellido(), this.getOficio(), this.getDir(), 
                this.getFechaAlta().toString(), this.getSalario(), this.getComision());
    }

}


