DROP TABLE TAB_DEP;
DROP TYPE V_EMPLE;
DROP TYPE T_EMPLE;
DROP TYPE T_DEP;

CREATE OR REPLACE TYPE T_DEP AS OBJECT (
    DEPT_NO NUMBER(2),
    DNOMBRE VARCHAR2(15),
    LOC VARCHAR2(15),

    MEMBER PROCEDURE SET_DEPT_NO(id NUMBER),
    MEMBER FUNCTION GET_DEPT_NO RETURN NUMBER,

    MEMBER PROCEDURE SET_DNOMBRE(DNOMBREV VARCHAR2),
    MEMBER FUNCTION GET_DNOMBRE RETURN VARCHAR2,

    MEMBER PROCEDURE SET_LOC(LOCV VARCHAR2),
    MEMBER FUNCTION GET_LOC RETURN VARCHAR2

);
/

CREATE OR REPLACE TYPE BODY T_DEP AS
    MEMBER PROCEDURE SET_DEPT_NO(id NUMBER) IS
    BEGIN
        DEPT_NO := id;
    END;

    MEMBER FUNCTION GET_DEPT_NO RETURN NUMBER IS
    BEGIN
        RETURN DEPT_NO;
    END;

    MEMBER PROCEDURE SET_DNOMBRE (DNOMBREV VARCHAR2) IS
    BEGIN
        DNOMBRE := DNOMBREV;
    END;

    MEMBER FUNCTION GET_DNOMBRE RETURN VARCHAR2 IS
    BEGIN
        RETURN DNOMBRE;
    END;

    MEMBER PROCEDURE SET_LOC (LOCV VARCHAR2) IS
    BEGIN
        LOC := LOCV;
    END;

    MEMBER FUNCTION GET_LOC RETURN VARCHAR2 IS
    BEGIN
        RETURN LOC;
    END;
END;
/

CREATE OR REPLACE TYPE T_EMPLE AS OBJECT (
    EMP_NO NUMBER(4),
    APELLIDO VARCHAR2(10),
    OFICIO VARCHAR2(10),
    DIR NUMBER(4),
    FECHA_ALT DATE,
    SALARIO NUMBER(6,2),
    COMISION NUMBER(6,2),
    DEPT_NO T_DEP,

    MEMBER PROCEDURE SET_EMP_NO (EMP_NO NUMBER),
    MEMBER FUNCTION GET_EMP_NO RETURN NUMBER,

    MEMBER PROCEDURE SET_APELLIDO (APELLIDO VARCHAR2),
    MEMBER FUNCTION GET_APELLIDO RETURN VARCHAR2,

    MEMBER PROCEDURE SET_OFICIO (OFICIO VARCHAR2),
    MEMBER FUNCTION GET_OFICIO RETURN VARCHAR2,

    MEMBER PROCEDURE SET_DIR (DIR NUMBER),
    MEMBER FUNCTION GET_DIR RETURN NUMBER,

    MEMBER PROCEDURE SET_FECHA_ALT (FECHA_ALT DATE),
    MEMBER FUNCTION GET_FECHA_ALT RETURN DATE,

    MEMBER PROCEDURE SET_SALARIO (SALARIO NUMBER),
    MEMBER FUNCTION GET_SALARIO RETURN NUMBER,

    MEMBER PROCEDURE SET_COMISION (COMISION NUMBER),
    MEMBER FUNCTION GET_COMISION RETURN NUMBER,

    MEMBER PROCEDURE SET_DEPT_NO (DEPT_NO T_DEP),
    MEMBER FUNCTION GET_DEPT_NO RETURN T_DEP
);
/

CREATE OR REPLACE TYPE BODY T_EMPLE AS
    MEMBER PROCEDURE SET_EMP_NO (EMP_NOV NUMBER) IS
    BEGIN
        EMP_NO := EMP_NOV;
    END;

    MEMBER FUNCTION GET_EMP_NO RETURN NUMBER IS
    BEGIN
        RETURN EMP_NO;
    END;

    MEMBER PROCEDURE SET_APELLIDO (APELLIDOV VARCHAR2) IS
    BEGIN
        APELLIDO := APELLIDOV;
    END;

    MEMBER FUNCTION GET_APELLIDO RETURN VARCHAR2 IS
    BEGIN
        RETURN APELLIDO;
    END;

    MEMBER PROCEDURE SET_OFICIO (OFICIOV VARCHAR2) IS
    BEGIN
        OFICIO := OFICIOV;
    END;

    MEMBER FUNCTION GET_OFICIO RETURN VARCHAR2 IS
    BEGIN
        RETURN OFICIO;
    END;

    MEMBER PROCEDURE SET_DIR (DIRV NUMBER) IS
    BEGIN
        DIR := DIRV;
    END;

    MEMBER FUNCTION GET_DIR RETURN NUMBER IS
    BEGIN
        RETURN DIR;
    END;

    MEMBER PROCEDURE SET_FECHA_ALT (FECHA_ALTV DATE) IS
    BEGIN
        FECHA_ALT := FECHA_ALTV;
    END;

    MEMBER FUNCTION GET_FECHA_ALT RETURN DATE IS
    BEGIN
        RETURN FECHA_ALT;
    END;

    MEMBER PROCEDURE SET_SALARIO (SALARIOV NUMBER) IS
    BEGIN
        SALARIO := SALARIOV;
    END;

    MEMBER FUNCTION GET_SALARIO RETURN NUMBER IS
    BEGIN
        RETURN SALARIO;
    END;

    MEMBER PROCEDURE SET_COMISION (COMISIONV NUMBER) IS
    BEGIN
        COMISION := COMISIONV;
    END;

    MEMBER FUNCTION GET_COMISION RETURN NUMBER IS
    BEGIN
        RETURN COMISION;
    END;

    MEMBER PROCEDURE SET_DEPT_NO (DEPT_NOV T_DEP) IS
    BEGIN
        DEPT_NO := DEPT_NOV;
    END;

    MEMBER FUNCTION GET_DEPT_NO RETURN T_DEP IS
    BEGIN
        RETURN DEPT_NO;
    END;
END;
/

CREATE OR REPLACE TYPE V_EMPLE AS VARRAY(20) OF T_EMPLE;
/

CREATE TABLE TAB_DEP(
    VARRAY_EMP V_EMPLE,
    DEPART T_DEP
);
/

CREATE OR REPLACE PROCEDURE inserFilas AS
    dep T_DEP := T_DEP(NULL, NULL, NULL);
    emp T_EMPLE := T_EMPLE(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
    varrayEmp V_EMPLE := V_EMPLE();
BEGIN
    --PARA CADA DEPARTAMENTO DE LA TABLA
    FOR recDep IN (SELECT DEPT_NO, DNOMBRE, LOC FROM DEPARTAMENTOS) LOOP
        --PARA CADA EMPLEADO DEL DEPARTAMENTO
        varrayEmp := V_EMPLE();
        dep := T_DEP(DEPT_NO => recDep.DEPT_NO, DNOMBRE => recDep.DNOMBRE, LOC => recDep.LOC);
        FOR rec IN (SELECT EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, SALARIO, COMISION FROM EMPLEADOS WHERE DEPT_NO = dep.DEPT_NO) LOOP
                BEGIN
                    varrayEmp.EXTEND;
                    emp := T_EMPLE(EMP_NO => rec.EMP_NO, APELLIDO => rec.APELLIDO, OFICIO => rec.OFICIO, DIR => rec.DIR, FECHA_ALT => REC.FECHA_ALT, SALARIO => REC.SALARIO, COMISION => REC.COMISION, DEPT_NO => dep);
                    varrayEmp(varrayEmp.last) := emp;
                end;
        end loop;

        INSERT INTO TAB_DEP VALUES(varrayEmp, dep);

    end loop;

END;

CALL inserFilas();

DECLARE
    cuenta number;
BEGIN
    for fila IN (SELECT T.DEPART, T.VARRAY_EMP FROM TAB_DEP T) LOOP
        DBMS_OUTPUT.PUT_LINE(fila.DEPART.DNOMBRE);
        cuenta := fila.VARRAY_EMP.COUNT;

        for i IN 1..fila.VARRAY_EMP.COUNT LOOP
            DBMS_OUTPUT.PUT_LINE('    '||fila.VARRAY_EMP(i).SALARIO||'  '||fila.VARRAY_EMP(i).APELLIDO);
            end loop;

    end loop;
END;
