package pojo;
// Generated 25 feb. 2024 18:48:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private String nombre;
     private String localidad;
     private Set empleados = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(String nombre) {
        this.nombre = nombre;
    }
    public Departamento(String nombre, String localidad, Set empleados) {
       this.nombre = nombre;
       this.localidad = localidad;
       this.empleados = empleados;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


