package pruebahibernate;
// Generated 30 nov. 2023 18:04:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private int empNo;
     private String apellido;
     private String oficio;
     private Integer dir;
     private Date fechaAlta;
     private Double salario;
     private Double comision;
     private Integer deptNo;

    public Empleados() {
    }

	
    public Empleados(int empNo) {
        this.empNo = empNo;
    }
    public Empleados(int empNo, String apellido, String oficio, Integer dir, Date fechaAlta, Double salario, Double comision, Integer deptNo) {
       this.empNo = empNo;
       this.apellido = apellido;
       this.oficio = oficio;
       this.dir = dir;
       this.fechaAlta = fechaAlta;
       this.salario = salario;
       this.comision = comision;
       this.deptNo = deptNo;
    }
   
    public int getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(int empNo) {
        this.empNo = empNo;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getOficio() {
        return this.oficio;
    }
    
    public void setOficio(String oficio) {
        this.oficio = oficio;
    }
    public Integer getDir() {
        return this.dir;
    }
    
    public void setDir(Integer dir) {
        this.dir = dir;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Double getSalario() {
        return this.salario;
    }
    
    public void setSalario(Double salario) {
        this.salario = salario;
    }
    public Double getComision() {
        return this.comision;
    }
    
    public void setComision(Double comision) {
        this.comision = comision;
    }
    public Integer getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(Integer deptNo) {
        this.deptNo = deptNo;
    }




}


